baseURL = "https://profwilliammelo.github.io/williammelo/" #precisa colocar site inteiro a ser hospedado
languageCode = "en"
DefaultContentLanguage = "en"
title = "William Melo"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
publishDir = "docs/" #precisa adicionar isso para publicar no git hub pages

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
